### ISSUE TITLE
WebNowPlaying-Library ETA?

### ISSUE THREAD

**Issue by YasogaN** [keifufu/WebNowPlaying#28]
Hi,
Sorry to disturb you like this by creating issues,  I just wanted to know the ETA of releasing the WebNowPlaying-Library
Thanks!

PS: Sorry for disturbing you.

**Comment by keifufu** [comment]
The new library and CLI adapter are just about done but it might take me a few weeks to release them.

I see you forked PyWNP and noted `This repo is currently the same as PyWNP by keifufu. This repo will be updated when the WebNowPlaying-Library is released`.

This new library will contain language bindings, as it is written in C and making bindings for it should be possible for most other languages.

I deprecated both the Python and C# libraries to instead create bindings.

It would be greatly appreciated if you contribute to `keifufu/WebNowPlaying-Library` rather than maintaining your own fork on GitHub/PyPI.

Don't worry about asking questions by the way.

**Comment by YasogaN** [comment]
Thank you for letting me know about the ETC!

I would do my best to contribute towards `keifufu/WebNowPlaying-Library`, However I am still new to programming and the only language i am fully familiar with is JS. (Even though i create python scripts, i dislike python and don't know much of it). 

I haven't even touched any other languages (Excluding html and css), so I might be pretty useless...

**Comment by keifufu** [comment]
The library is on GitHub now, but it will remain without releases until further testing has been done. I would appreciate it if you removed your PyWNP fork, unless you want do actually maintain / expand the Python version of course.
