### ISSUE TITLE
Firefox Addon "Bad source or badly formatted message, skipping" from bootstrap-content-message-handler.js - console spam

### ISSUE THREAD

**Issue by OneNot** [keifufu/WebNowPlaying#30]
I'm seeing a spam of:
```
Handling window message [bootstrap-content-message-handler.js:167:21](moz-extension://ab53cc0e-d7fc-4dfe-8d84-71c9e7ffc4e0/content/bootstrap-content-message-handler.js)
Bad source or badly formatted message, skipping. [bootstrap-content-message-handler.js:171:25](moz-extension://ab53cc0e-d7fc-4dfe-8d84-71c9e7ffc4e0/content/bootstrap-content-message-handler.js)
```
in the browser console in Firefox v121.0.1 using WebNowPlaying v3.0.1. As in, like 10 times a second or something.
I'm not sure what it's actually skipping, or how much of a problem it actually is. The spam certainly wasn't helpful when trying use the console to debug my userscripts on youtube though lol

**Comment by OneNot** [comment]
Hmm interesting... You are right, it's Bitwarden, but the behaviour starts and stops as I enable/disable the WebNowPlaying addon...
[here's the file](https://github.com/keifufu/WebNowPlaying/files/13954006/bootstrap-content-message-handler.zip) (zipped because apparently Github doesn't let you upload .js files here)

**Comment by keifufu** [comment]
I can replicate this now and this is indeed very annoying.
WebNowPlaying uses window messages to communicate, just like BitWarden seems to do for some cases. The issue is that BitWarden decides to log on each message, no matter what data it contains. I could "fix" the "Bad source..." warning but it'd still print "Handling window message" annoyingly. Consider opening a PR or issue on BitWarden to only log if a message came from its own scripts. As a temporary workaround you can just disable debug messages in the developer tools since these are printed with console.debug.

**Comment by OneNot** [comment]
Got it. Thanks for looking into it.
